import 'category.dart';

/// Expense model class
/// Represents a single expense entry with all its properties
class Expense {
  final int? id; // Nullable because it's auto-generated by the database
  final String name;
  final double amount;
  final DateTime date;
  final ExpenseCategory category;

  Expense({
    this.id,
    required this.name,
    required this.amount,
    required this.date,
    required this.category,
  });

  /// Converts an Expense object to a Map for database storage
  /// This is used when inserting or updating expenses in SQLite
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'amount': amount,
      'date': date.toIso8601String(), // Convert DateTime to String for storage
      'category': category.index, // Store the enum as an integer index
    };
  }

  /// Creates an Expense object from a Map retrieved from the database
  /// This is used when reading expenses from SQLite
  factory Expense.fromMap(Map<String, dynamic> map) {
    return Expense(
      id: map['id'] as int?,
      name: map['name'] as String,
      amount: map['amount'] as double,
      date: DateTime.parse(map['date'] as String), // Convert String back to DateTime
      category: ExpenseCategory.values[map['category'] as int], // Convert index back to enum
    );
  }

  /// Creates a copy of this Expense with some fields replaced with new values
  /// Useful for updating expenses
  Expense copyWith({
    int? id,
    String? name,
    double? amount,
    DateTime? date,
    ExpenseCategory? category,
  }) {
    return Expense(
      id: id ?? this.id,
      name: name ?? this.name,
      amount: amount ?? this.amount,
      date: date ?? this.date,
      category: category ?? this.category,
    );
  }
}
